#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='nvim'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='nvim'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# original settings
# linuxbrew
# if [ -f /proc/sys/fs/binfmt_misc/WSLInterop ]; then
#   eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
# fi

# Time Stamp
if [[ ! -d ~/TimeStamp ]]; then
  git clone git@github.com:sonarAIT/TimeStamp.git $HOME/TimeStamp
fi
zsh -c "~/TimeStamp/stamp.sh &" >/dev/null 2>&1

# byobu
if [[ "$(uname)" == 'Darwin' ]]; then
  _byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true
fi
if [ -f /proc/sys/fs/binfmt_misc/WSLInterop ]; then
  _byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true
fi

# Golang
export PATH=$PATH:/usr/local/go/bin
