#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
DOTFILES_PATH=$HOME/dotfiles
ZSH_PATH=$DOTFILES_PATH/zsh

# import theme
source $ZSH_PATH/theme/default.zsh

# import zsh scripts
if [ -d $ZSH_PATH ]; then
  source $ZSH_PATH/alias.zsh
  source $ZSH_PATH/bindkey.zsh
  source $ZSH_PATH/dir.zsh
  source $ZSH_PATH/config.zsh
fi

