# disable configration wizard
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

# elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context battery dir_writable dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time time ram background_jobs)

# prompt settings
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "

# os icon
if [[ "$(uname)" == 'Darwin' ]]; then
  POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=" "
else
  POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=" "
fi

# context
POWERLEVEL9K_CONTEXT_TEMPLATE="%n"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="white"

# battery
POWERLEVEL9K_BATTERY_LOW_COLOR="magenta"
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="cyan"
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="cyan"
POWERLEVEL9K_BATTERY_LOW_THRESHOLD="15"
POWERLEVEL9K_BATTERY_STAGES=("", "", "", "", "", "", "")

# dir writable
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="black"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="magenta"

# dir
POWERLEVEL9K_DIR_BACKGROUND="cyan"
POWERLEVEL9K_ETC_ICON="\ueaf8 "
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1

# vcs
POWERLEVEL9K_VCS_BACKGROUND="white"

# status
POWERLEVEL9K_STATUS_OK_FOREGROUND="cyan"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="black"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="magenta"

# execution time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=black
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=white

# time
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M 20%y/%m/%d}"

# RAM
POWERLEVEL9K_RAM_BACKGROUND="white"

# background jobs
POWERLEVEL9K_BACKGROUND_JOBS_ICON="\ueaf8 "
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=true

